name: '[CD]'
run-name: Trigger PUSH
on:
  workflow_dispatch:
    inputs:
      deploy-target:
        description: "Deploy to ..."
        required: true
        type: choice
        options:
          - staging_foo
          - staging_bar
          - staging_hoge
          - staging_piyo
jobs:
  dispatch-input:
    name: Dispatch Input
    runs-on: ubuntu-22.04
    steps:
      - run: echo "You selected \"${{ inputs.deploy-target }}\""

  wait-for-deploy:
    name: hoge
    runs-on: ubuntu-22.04
    environment:
      name: Production
    steps:
      - run: echo "Hello!"

  empty-env:
    name: empty-env
    runs-on: ubuntu-22.04
    environment:
      name: trigger
    steps:
      - run: echo "Do empty-env"
    needs:
      - wait-for-deploy
      - dispatch-input
